vich_uploader:
    db_driver: orm

    mappings:
        avatar_image:
            uri_prefix: /img/avatars
            upload_destination: '%kernel.project_dir%/public/img/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        banner_image:
            uri_prefix: /img/banners
            upload_destination: '%kernel.project_dir%/public/img/banners'
            namer: Vich\UploaderBundle\Naming\UniqidNamer